import { File, Inbox, LucideIcon, Send } from "lucide-react";

export type SidebarItem = {
  title: string;
  icon: LucideIcon;
  variant: "default" | "ghost";
  url: string;
  name: string;
  items: SidebarItem[];
};

export const navItems: SidebarItem[] = [
  {
    title: "Dashboard",
    icon: Inbox,
    variant: "ghost",
    url: "/system",
    name: "Dashboard",
    items: [
      {
        title: "Users & Roles",
        icon: Inbox,
        variant: "ghost",
        url: "/system/user-roles",
        name: "Users & Roles",
        items: [
          {
            title: "Users",
            icon: Inbox,
            variant: "ghost",
            url: "/system/user-roles/users",
            name: "Users",
            items: [],
          },
          {
            title: "Roles",
            icon: Inbox,
            variant: "ghost",
            url: "/system/user-roles/roles",
            name: "Roles",
            items: [],
          },
          {
            title: "Parties",
            icon: Inbox,
            variant: "ghost",
            url: "/system/user-roles/parties",
            name: "Parties",
            items: [],
          },
          {
            title: "Devices",
            icon: Inbox,
            variant: "ghost",
            url: "/system/user-roles/devices",
            name: "Devices",
            items: [],
          },
        ],
      },
      {
        title: "Scheduled tasks",
        icon: Inbox,
        variant: "ghost",
        url: "/system/scheduled-tasks",
        name: "Scheduled tasks",
        items: [],
      },
      {
        title: "Settings",
        icon: Inbox,
        variant: "ghost",
        url: "/system/settings",
        name: "Settings",
        items: [
          {
            title: "Chung",
            icon: Inbox,
            variant: "ghost",
            url: "/system/settings/common",
            name: "Chung",
            items: [],
          },
          {
            title: "Sequence",
            icon: Inbox,
            variant: "ghost",
            url: "/system/settings/sequence",
            name: "Sequence",
            items: [],
          },
          {
            title: "Mẫu In",
            icon: Inbox,
            variant: "ghost",
            url: "/system/settings/print-template",
            name: "Mẫu In",
            items: [],
          },
          {
            title: "Mẫu email",
            icon: Inbox,
            variant: "ghost",
            url: "/system/settings/email-template",
            name: "Mẫu email",
            items: [],
          },
          {
            title: "Tech - Settings",
            icon: Inbox,
            variant: "ghost",
            url: "/system/settings/tech-settings",
            name: "Tech - Settings",
            items: [],
          },
          {
            title: "Tech - Settings enum",
            icon: Inbox,
            variant: "ghost",
            url: "/system/settings/tech-settings-enum",
            name: "Tech - Settings enum",
            items: [],
          },
        ],
      },
      {
        title: "Logs",
        icon: Inbox,
        variant: "ghost",
        url: "/system/logs",
        name: "Logs",
        items: [],
      },
    ],
  },
  {
    title: "Hệ thống",
    icon: File,
    variant: "ghost",
    url: "/system",
    name: "System",
    items: [
      {
        title: "Users & Roles",
        icon: Inbox,
        variant: "ghost",
        url: "/system/user-roles",
        name: "Users & Roles",
        items: [
          {
            title: "Users",
            icon: Inbox,
            variant: "ghost",
            url: "/system/user-roles/users",
            name: "Users",
            items: [],
          },
          {
            title: "Roles",
            icon: Inbox,
            variant: "ghost",
            url: "/system/user-roles/roles",
            name: "Roles",
            items: [],
          },
          {
            title: "Parties",
            icon: Inbox,
            variant: "ghost",
            url: "/system/user-roles/parties",
            name: "Parties",
            items: [],
          },
          {
            title: "Devices",
            icon: Inbox,
            variant: "ghost",
            url: "/system/user-roles/devices",
            name: "Devices",
            items: [],
          },
        ],
      },
      {
        title: "Scheduled tasks",
        icon: Inbox,
        variant: "ghost",
        url: "/system/scheduled-tasks",
        name: "Scheduled tasks",
        items: [],
      },
      {
        title: "Settings",
        icon: Inbox,
        variant: "ghost",
        url: "/system/settings",
        name: "Settings",
        items: [
          {
            title: "Chung",
            icon: Inbox,
            variant: "ghost",
            url: "/system/settings/common",
            name: "Chung",
            items: [],
          },
          {
            title: "Sequence",
            icon: Inbox,
            variant: "ghost",
            url: "/system/settings/sequence",
            name: "Sequence",
            items: [],
          },
          {
            title: "Mẫu In",
            icon: Inbox,
            variant: "ghost",
            url: "/system/settings/print-template",
            name: "Mẫu In",
            items: [],
          },
          {
            title: "Mẫu email",
            icon: Inbox,
            variant: "ghost",
            url: "/system/settings/email-template",
            name: "Mẫu email",
            items: [],
          },
          {
            title: "Tech - Settings",
            icon: Inbox,
            variant: "ghost",
            url: "/system/settings/tech-settings",
            name: "Tech - Settings",
            items: [],
          },
          {
            title: "Tech - Settings enum",
            icon: Inbox,
            variant: "ghost",
            url: "/system/settings/tech-settings-enum",
            name: "Tech - Settings enum",
            items: [],
          },
        ],
      },
      {
        title: "Logs",
        icon: Inbox,
        variant: "ghost",
        url: "/system/logs",
        name: "Logs",
        items: [],
      },
    ],
  },
  {
    title: "Merchant",
    icon: File,
    variant: "ghost",
    url: "/merchant",
    name: "Merchant",
    items: [
      {
        title: "Requests",
        icon: File,
        variant: "ghost",
        url: "/merchant/requests",
        name: "Requests",
        items: [],
      },
      {
        title: "Chi hộ",
        icon: File,
        variant: "ghost",
        url: "/merchant/fundtransfer",
        name: "Chi hộ",
        items: [],
      },
      {
        title: "Thu hộ",
        icon: File,
        variant: "ghost",
        url: "/merchant/balance-change",
        name: "Thu hộ",
        items: [],
      },
      {
        title: "Thanh toán",
        icon: File,
        variant: "ghost",
        url: "/merchant/payments",
        name: "Thanh toán",
        items: [],
      },
      {
        title: "Momo",
        icon: File,
        variant: "ghost",
        url: "/merchant/momo",
        name: "Momo",
        items: [
          {
            title: "Nhận",
            icon: File,
            variant: "ghost",
            url: "/merchant/momo/momo-debit",
            name: "Nhận",
            items: [],
          },
          {
            title: "Rút",
            icon: File,
            variant: "ghost",
            url: "/merchant/momo/momo-transfer",
            name: "Rút",
            items: [],
          },
        ],
      },
      {
        title: "Tools",
        icon: File,
        variant: "ghost",
        url: "/merchant/tools",
        name: "Tools",
        items: [
          {
            title: "TEST API",
            icon: File,
            variant: "ghost",
            url: "/merchant/tools/test-api",
            name: "TEST API",
            items: [],
          },
          {
            title: "UAT",
            icon: File,
            variant: "ghost",
            url: "/merchant/tools/uat",
            name: "UAT",
            items: [],
          },
          {
            title: "Tài liệu",
            icon: File,
            variant: "ghost",
            url: "/merchant/tools/document",
            name: "Tài liệu",
            items: [],
          },
          {
            title: "Cập nhật gd chi hộ",
            icon: File,
            variant: "ghost",
            url: "/merchant/tools/update_ft",
            name: "Cập nhật gd chi hộ",
            items: [],
          },
          {
            title: "Vớt giao dịch thu hộ",
            icon: File,
            variant: "ghost",
            url: "/merchant/tools/fetch_ft",
            name: "Vớt giao dịch thu hộ",
            items: [],
          },
        ],
      },
      {
        title: "Cài đặt",
        icon: File,
        variant: "ghost",
        url: "/merchant/settings",
        name: "Cài đặt",
        items: [
          {
            title: "Bảng phí",
            icon: File,
            variant: "ghost",
            url: "/merchant/settings/fee",
            name: "Bảng phí",
            items: [],
          },
          {
            title: "Phí dịch vụ cho merchant",
            icon: File,
            variant: "ghost",
            url: "/merchant/settings/fee-config",
            name: "Phí dịch vụ cho merchant",
            items: [],
          },
          {
            title: "Rule phân luồng",
            icon: File,
            variant: "ghost",
            url: "/merchant/settings/rule",
            name: "Rule phân luồng",
            items: [],
          },
          {
            title: "Phân luồng",
            icon: File,
            variant: "ghost",
            url: "/merchant/settings/routes",
            name: "Phân luồng",
            items: [],
          },
          {
            title: "Merchant - User",
            icon: File,
            variant: "ghost",
            url: "/merchant/settings/user",
            name: "Merchant - User",
            items: [],
          },
          {
            title: "Nhà cung cấp",
            icon: File,
            variant: "ghost",
            url: "/merchant/settings/providers",
            name: "Nhà cung cấp",
            items: [],
          },
          {
            title: "Mã thu hộ",
            icon: File,
            variant: "ghost",
            url: "/merchant/settings/collection-code",
            name: "Mã thu hộ",
            items: [],
          },
          {
            title: "Số thẻ tăng hạn mức",
            icon: File,
            variant: "ghost",
            url: "/merchant/settings/account-vcard",
            name: "Số thẻ tăng hạn mức",
            items: [],
          },
          {
            title: "Chính sách dịch vụ",
            icon: File,
            variant: "ghost",
            url: "/merchant/settings/policy",
            name: "Chính sách dịch vụ",
            items: [],
          },
        ],
      },
    ],
  },
  {
    title: "Báo cáo",
    icon: File,
    variant: "ghost",
    url: "/report",
    name: "Báo cáo",
    items: [
      {
        title: "Báo cáo",
        icon: File,
        variant: "ghost",
        url: "/report/annunciate",
        name: "Báo cáo",
        items: [],
      },
    ],
  },
  {
    title: "Chi nội bộ",
    icon: File,
    variant: "ghost",
    url: "/internalpay",
    name: "Chi nội bộ",
    items: [
      {
        title: "Lệnh chi",
        icon: File,
        variant: "ghost",
        url: "/internalpay/payment",
        name: "Lệnh chi",
        items: [],
      },
    ],
  },
  {
    title: "Cash by Code",
    icon: File,
    variant: "ghost",
    url: "/cash-by-code",
    name: "Cash by Code",
    items: [
      {
        title: "Giao dịch",
        icon: File,
        variant: "ghost",
        url: "/cash-by-code/transaction",
        name: "Giao dịch",
        items: [],
      },
      {
        title: "SMS",
        icon: File,
        variant: "ghost",
        url: "/cash-by-code/sms",
        name: "SMS",
        items: [],
      },
    ],
  },
  {
    title: "App metrics",
    icon: File,
    variant: "ghost",
    url: "/appmetrics",
    name: "App metrics",
    items: [],
  },
];
